### ISSUE TITLE
Disable event catcher on systems that do not support SSE

### ISSUE THREAD

**Issue by tadeboro** [ManageIQ/manageiq-providers-redfish#90]
**Short description:** If the physical server's BMC does not support SSE for sending events, event catcher will repeatedly try to reconnect to a non-existing endpoint, incurring a substantial load on the Redfish API and increasing the chances of failure.

**How to replicate the issue:**

 1. Add a new physical server whose BMC does not support SSE to ManageIQ.
 2. Watch the error message about not being able to connect to the SSE endpoint appear in ManageIQ's logs every few seconds.

**Expected behavior:** ManageIQ should stop trying to reconnect after a set number of tries. Alternatively, we should be able to activate or deactivate the event catcher when we are adding a new physical server to ManageIQ.

**Details:**

Sample error message that appears in the logs:

```
[----] I, [2019-08-15T07:12:11.479596 #8541:f305fc]  INFO -- : MIQ(ManageIQ::Providers::Redfish::PhysicalInfraManager::EventCatcher::Runner#start_event_monitor) EMS [10.21.254.18] as [manageiq] Started Event Monitor Thread
[----] I, [2019-08-15T07:12:12.481120 #8541:f305fc]  INFO -- : MIQ(ManageIQ::Providers::Redfish::PhysicalInfraManager::EventCatcher::Runner#do_work) EMS [10.21.254.18] as [manageiq] Event Monitor Thread gone. Restarting...
[----] I, [2019-08-15T07:12:12.481327 #8541:f305fc]  INFO -- : MIQ(ManageIQ::Providers::Redfish::PhysicalInfraManager::EventCatcher::Runner#start_event_monitor) EMS [10.21.254.18] as [manageiq] Validating Connection/Credentials
[----] I, [2019-08-15T07:12:12.481372 #8541:f305fc]  INFO -- : MIQ(ManageIQ::Providers::Redfish::PhysicalInfraManager#with_provider_connection) Connecting through ManageIQ::Providers::Redfish::PhysicalInfraManager: [hp01]
[----] I, [2019-08-15T07:12:12.920818 #8541:f305fc]  INFO -- : MIQ(ManageIQ::Providers::Redfish::PhysicalInfraManager::EventCatcher::Runner#start_event_monitor) EMS [10.21.254.18] as [manageiq] Starting Event Monitor Thread
[----] I, [2019-08-15T07:12:12.921031 #8541:478bac8]  INFO -- : MIQ(ManageIQ::Providers::Redfish::PhysicalInfraManager#with_provider_connection) Connecting through ManageIQ::Providers::Redfish::PhysicalInfraManager: [hp01]
[----] E, [2019-08-15T07:12:13.743776 #8541:478bac8] ERROR -- : MIQ(ManageIQ::Providers::Redfish::PhysicalInfraManager::EventCatcher::Runner#start_event_monitor) EMS [10.21.254.18] as [manageiq] Event Monitor Thread aborted because [undefined method `listen' for nil:NilClass]
[----] E, [2019-08-15T07:12:13.743867 #8541:478bac8] ERROR -- : [NoMethodError]: undefined method `listen' for nil:NilClass  Method:[block (2 levels) in <class:LogProxy>]
[----] E, [2019-08-15T07:12:13.743897 #8541:478bac8] ERROR -- : /usr/local/lib/ruby/gems/2.5.0/bundler/gems/manageiq-providers-redfish-c8c92b27d884/app/models/manageiq/providers/redfish/physical_infra_manager/event_catcher/runner.rb:5:in `monitor_events'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/event_catcher/runner.rb:161:in `block in start_event_monitor'
```

**Comment by vwbusguy** [comment]
I found this comment (also by the issue author) to be helpful as a workaround in the meantime: https://github.com/ManageIQ/manageiq-providers-redfish/issues/89#issuecomment-521559486
